// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_tL1KUxHPO53mUpGdbvM7VdaK7S2ZhA',
    appId: '1:272581182701:web:44f381c09bfe57df18b8e4',
    messagingSenderId: '272581182701',
    projectId: 'loginexample-66765',
    authDomain: 'loginexample-66765.firebaseapp.com',
    storageBucket: 'loginexample-66765.firebasestorage.app',
    measurementId: 'G-9K652ZLHCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANET_urnN76sGStTFWl8vkq3uXlbLz6WY',
    appId: '1:272581182701:android:b0ffc4741583297018b8e4',
    messagingSenderId: '272581182701',
    projectId: 'loginexample-66765',
    storageBucket: 'loginexample-66765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23WH-o7PUNJ2NK-aBD_Ag_QO7x2mmYYw',
    appId: '1:272581182701:ios:e441d64be181d34218b8e4',
    messagingSenderId: '272581182701',
    projectId: 'loginexample-66765',
    storageBucket: 'loginexample-66765.firebasestorage.app',
    iosBundleId: 'com.example.andrewsaba.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23WH-o7PUNJ2NK-aBD_Ag_QO7x2mmYYw',
    appId: '1:272581182701:ios:e441d64be181d34218b8e4',
    messagingSenderId: '272581182701',
    projectId: 'loginexample-66765',
    storageBucket: 'loginexample-66765.firebasestorage.app',
    iosBundleId: 'com.example.andrewsaba.loginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG_tL1KUxHPO53mUpGdbvM7VdaK7S2ZhA',
    appId: '1:272581182701:web:e1661ffa02664c8c18b8e4',
    messagingSenderId: '272581182701',
    projectId: 'loginexample-66765',
    authDomain: 'loginexample-66765.firebaseapp.com',
    storageBucket: 'loginexample-66765.firebasestorage.app',
    measurementId: 'G-2H5FRB25FQ',
  );
}
